# Background and foreground colors
background = #09100E
foreground = #DBD7EC

# Standard colors
palette = 0=#09100E
palette = 1=#b187bc
palette = 2=#95c9ff
palette = 3=#ffd2ff
palette = 4=#8079bc
palette = 5=#be9cee
palette = 6=#b8d9ff
palette = 7=#DBD7EC

# Bright colors
palette = 8=#626967
palette = 9=#cd98db
palette = 10=#9ce0ff
palette = 11=#ffc6ff
palette = 12=#958cde
palette = 13=#d9acff
palette = 14=#c4ebff
palette = 15=#f5f3ff
