$color = rgba(9, 16, 14, 1)
$inner_color = rgba(9, 16, 14, 0.66)
$outer_color = rgba(190, 156, 238, 1)
$font_color = rgba(219, 215, 236, 1)
$placeholder_color = rgba(219, 215, 236, 0.7)
$check_color = rgba(184, 217, 255, 1)
