background            #09100E
foreground            #DBD7EC

# black
color0  #09100E
color8  #626967

# red
color1  #b187bc
color9  #cd98db

# green
color2  #95c9ff
color10 #9ce0ff

# yellow
color3  #ffd2ff
color11 #ffc6ff

# blue
color4  #8079bc
color12 #958cde

# magenta
color5  #be9cee
color13 #d9acff

#cyan
color6  #b8d9ff
color14 #c4ebff

#white
color7  #DBD7EC
color15 #f5f3ff


