# Background and foreground colors
background = #0F141B
foreground = #F2E9C1

# Standard colors
palette = 0=#0F141B
palette = 1=#b5775e
palette = 2=#588b57
palette = 3=#7cc8ad
palette = 4=#667cba
palette = 5=#7779b7
palette = 6=#4c8ba4
palette = 7=#F2E9C1

# Bright colors
palette = 8=#6b6f74
palette = 9=#e19a79
palette = 10=#76b36c
palette = 11=#90e7c4
palette = 12=#889eee
palette = 13=#9b9bea
palette = 14=#6bb0d1
palette = 15=#fbed9e
