background            #0F141B
foreground            #F2E9C1

# black
color0  #0F141B
color8  #6b6f74

# red
color1  #b5775e
color9  #e19a79

# green
color2  #588b57
color10 #76b36c

# yellow
color3  #7cc8ad
color11 #90e7c4

# blue
color4  #667cba
color12 #889eee

# magenta
color5  #7779b7
color13 #9b9bea

#cyan
color6  #4c8ba4
color14 #6bb0d1

#white
color7  #F2E9C1
color15 #fbed9e


