# Background and foreground colors
background = #030A00
foreground = #FEF2F4

# Standard colors
palette = 0=#030A00
palette = 1=#c7675d
palette = 2=#efd46f
palette = 3=#6a8343
palette = 4=#a29cf3
palette = 5=#ab59ab
palette = 6=#756dc9
palette = 7=#FEF2F4

# Bright colors
palette = 8=#5c5f59
palette = 9=#f6887a
palette = 10=#ffe211
palette = 11=#8baa52
palette = 12=#c7bbff
palette = 13=#d876de
palette = 14=#9a8cff
palette = 15=#ffdde7
