$color = rgba(3, 10, 0, 1)
$inner_color = rgba(3, 10, 0, 0.66)
$outer_color = rgba(171, 89, 171, 1)
$font_color = rgba(254, 242, 244, 1)
$placeholder_color = rgba(254, 242, 244, 0.7)
$check_color = rgba(117, 109, 201, 1)
